name: interactive_graph_view
description: "A performant rendering library for displaying and manipulating custom-defined graph structures through a simple and intuitive API with maximum control over the graph's look and feel."
version: 0.1.0
repository: https://github.com/JannikWinter/interactive_graph_view

environment:
  sdk: ^3.10.8
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_drawing: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
