name: interactive_graph_view
description: "With interactive_graph_view you can display, style and interact with any graph you define."
version: 0.0.0
homepage: https://github.com/JannikWinter/interactive_graph_view

environment:
  sdk: ^3.10.8
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_drawing: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
